name: psyplot_gui_docs
channels:
    - local
    - psyplot/label/master
    - conda-forge
dependencies:
    - python=3.8
    - scipy
    - netcdf4=1.5.7
    - h5py=3.4.0
    - hdf5=1.12.1
    - pytest-qt
    - psy-simple
    - psyplot-gui
    - pytest-cov
    - pip
    - pip:
      - tests/test_plugin/